### ISSUE TITLE
Error validating config file against schema file

### ISSUE THREAD

**Issue by januarharianto** [Sydney-Informatics-Hub/eeharvest#5]
Occurs most likely due to error in setting the schema.

If a config YAML has this (note, incomplete file, just showing necessary block):

```yaml

target_sources:
  GEE:
    preprocess:
      collection: LANDSAT/LC09/C02/T1_L2
      mask_clouds: True
      mask_probability: null
      reduce: median
      spectral: [NDVI, NDWI]
    download:
      bands: [NDVI, NDWI]
...

```

An error occurs validating `bands`.

```
YamaleError: Error validating data '../tests/data/test_001.yaml' with schema 'schema.yaml'
	target_sources.GEE.preprocess.spectral: '['NDVI', 'NDWI']' is not a str.
	target_sources.GEE.preprocess.spectral: '['NDVI', 'NDWI']' is not a null.
	target_sources.GEE.download.bands: '['NDVI', 'NDWI']' is not a str.
```

This can be fixed by adding `list(str())` to the schema
