### ISSUE TITLE
TypeError: 'bool' object is not iterable when running `auto()` on specific template

### ISSUE THREAD

**Issue by januarharianto** [Sydney-Informatics-Hub/eeharvest#7]
YAML template:

```yaml
target_bbox: [149.799, -30.31, 149.80, -30.309]
target_res: 6
date_min: 2022-10-01
date_max: 2022-12-01

target_sources:
  GEE:
    preprocess:
      collection: LANDSAT/LC08/C02/T1_L2
      mask_clouds: True
      mask_probability: null
      reduce: median
      spectral: NDVI
    download:
      bands: NDVI
```

Assuming this was `template.yaml`:

```py
eeharvest.auto(config="../configs/template.yaml")
```
When value is `NDVI` for the key `bands`, error occurs: `TypeError: 'bool' object is not iterable`.
This doesn't happen when the value is in a list i.e. `[NDVI]`
